version: '3.8'

services:
  slack_bot:
    image: grkamalteja/slack_bot:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: slack_bot
    container_name: slack_bot
    restart: unless-stopped
    command: sh -c 'cd notifier && gunicorn wsgi:earth_app --bind slack_bot:8000'
    # command: python notifier/wsgi.py
    volumes:
      - /home/ansible/repo/myNotifier/notifier/:/opt/app/slack_bot/notifier
    env_file:
      - .env

  slack_bot_nginx_proxy:
    image: grkamalteja/slack_bot_nginx_proxy:latest
    container_name: slack_bot_nginx_proxy
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - slack_bot
