version: '3.8'

services:
  slack_bot_gunicorn:
    image: grkamalteja/slack_bot:latest
    container_name: slack_bot
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/DockerFile
      target: python_3
    # command: gunicorn wsgi:app --bind slack_bot_gunicorn:8000
    command: python wsgi.py
    volumes:
      - /home/kamal/repo/myNotifier/hello.py:/opt/app/slack_bot/hello.py
    expose:
      - 8000
    # env_file:
    #   - .env
    networks:
      - traefik_default

  grkamalteja_nginx_proxy:
    image: grkamalteja/slack_bot_nginx_proxy:latest
    container_name: slack_bot_nginx_proxy
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/DockerFile
      target: nginx
    # expose:
    #   - 80
    ports:
      - 8080:80
    depends_on:
      - slack_bot_gunicorn
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.myredirect.redirectscheme.scheme=https
      - traefik.http.routers.slack_bot.middlewares=myredirect
      - traefik.http.routers.slack_bot.rule=Host(`slack_bot.grkamalteja.com`)
      - traefik.http.routers.slack_bot.entrypoints=web
      - traefik.http.routers.slack_bot-secure.rule=Host(`slack_bot.grkamalteja.com`)
      - traefik.http.routers.slack_bot-secure.entrypoints=websecure
      - traefik.http.routers.slack_bot-secure.tls.certresolver=myhttpchallenge
      - traefik.http.routers.slack_bot-secure.tls=true
      - traefik.http.services.slack_bot.loadbalancer.server.port=80

networks:
  traefik_default:
    external: true
